# config.local.yaml

# Example of overriding trading settings
trading:
  dry_run: false  # Set to false for real trading
  trade_amount: 1000  # Adjust trade amount as needed

# Example of overriding model paths
model:
  model_path: "models/local_trading_model.pkl"
  lstm_model_path: "models/local_lstm_trading_model.h5"
