trading:
  coins:
    - BTC
    - ETH
    - BNB
  dynamic_coins: true
  base_symbol: USDT
  buy_threshold: 1.005
  sell_threshold: 0.995
  trade_amount: 0.001
  max_daily_trades: 10
  timeframe: '1T'  # 1T = 1 Minute
  lookback: 200

model:
  test_size: 0.2
  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  model_path: 'models/trading_model.pkl'

execution:
  loop_interval: 60  # In seconds

database:
  primary: 'postgresql'
  secondary: 'mysql'

logging:
  file: 'logs/crypto_ai.log'
  level: 'INFO'
