# config.yaml

logging:
  level: INFO
  file: logs/crypto_ai.log

database:
  primary: postgresql  # or mysql
  secondary: mysql      # or postgresql
  # Add other database configurations as needed

api:
  data_source: cryptocompare  # or coingecko, simulated

trading:
  coins:
    - BTC/USDT
    - ETH/USDT
    # Add other trading pairs as needed
  trade_amount: 1000
  timeframe: '1H'
  lookback: 200
  buy_threshold: 1.002
  sell_threshold: 0.998
  max_daily_trades: 10
  dynamic_coins: false

model:
  model_path: models/trading_model.pkl
  retrain: true
  param_grid:
    n_estimators: [100, 200]
    max_depth: [10, 20]
    # Add other hyperparameters as needed

crawling:
  enabled: false
