---
# config.yaml

# API Configuration
api:
  data_source: simulated  # Options: 'simulated', 'cryptocompare', 'coingecko'
  # If using another API, add relevant keys here

# Trading Configuration
trading:
  coins: ["BTC", "ETH", "BNB"]
  dynamic_coins: true
  base_symbol: "USDT"
  buy_threshold: 1.005
  sell_threshold: 0.995
  trade_amount: 0.001
  max_daily_trades: 10

# Machine Learning Configuration
model:
  test_size: 0.2
  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  retrain: false

# Execution Settings
execution:
  loop_interval: 60  # in seconds

# Database Configuration
database:
  primary: "postgresql"  # Options: 'postgresql', 'mysql'
  secondary: "mysql"

# Logging Configuration
logging:
  level: INFO
  file: logs\crypto_ai.log

# Other Settings
settings:
  use_local_config: true
