# config.local.yaml

trading:
  trade_amount: 500  # Override trade amount to $500
  buy_threshold: 1.005  # Change buy threshold to 0.5% increase
  sell_threshold: 0.995  # Change sell threshold to 0.5% decrease

api:
  data_source: "simulated"  # Use simulated data for testing
