settings:
  use_local_config: false  # Set to true if you have 'config.local.yaml' for overrides

trading:
  coins: ["BTC", "ETH", "BNB"]
  dynamic_coins: true
  base_symbol: "USDT"  # Ensures trading pairs like 'BTC/USDT'
  buy_threshold: 1.005
  sell_threshold: 0.995
  trade_amount: 0.001
  max_daily_trades: 10
  timeframe: "1H"  # Timeframe for candlestick data
  lookback: 200    # Number of data points to fetch

model:
  test_size: 0.2
  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [None, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  retrain: true
  model_path: "models/trading_model.pkl"

execution:
  loop_interval: 60  # Time in seconds between each bot cycle

database:
  primary: "postgresql"  # Primary database type: "postgresql" or "mysql"
  secondary: "mysql"     # Secondary database type

logging:
  file: "logs/crypto_ai.log"
  level: "INFO"

api:
  data_source: "cryptocompare"  # Options: "cryptocompare", "coingecko", "simulated"

crawling:
  enabled: false
  websites:
    - name: "Crypto News Site"
      url: "https://www.coindesk.com/"
      parse_function: "parse_crypto_news"
    - name: "Crypto Data Site"
      url: "https://coinmarketcap.com/"
      parse_function: "parse_another_crypto_site"
